import os

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
POLYGON_API_KEY = os.getenv("POLYGON_API_KEY")
FINNHUB_API_KEY = os.getenv("FINNHUB_API_KEY")
ALPHA_VANTAGE_API_KEY = os.getenv("ALPHA_VANTAGE_API_KEY")
FRED_API_KEY = os.getenv("FRED_API_KEY")
AGENT_API_KEY = os.getenv("AGENT_API_KEY")
FMP_API_KEY = os.getenv("FMP_API_KEY")
COINGECKO_API_KEY = os.getenv("COINGECKO_API_KEY")
CMC_API_KEY = os.getenv("CMC_API_KEY")
ALTFINS_API_KEY = os.getenv("ALTFINS_API_KEY")
XAI_API_KEY = os.getenv("XAI_API_KEY")
