// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/closed-positions/BloombergTable.tsx": () => import("../components/mockups/closed-positions/BloombergTable.tsx"),
  "./components/mockups/closed-positions/PnLScorecard.tsx": () => import("../components/mockups/closed-positions/PnLScorecard.tsx"),
  "./components/mockups/closed-positions/TradeCardsGrid.tsx": () => import("../components/mockups/closed-positions/TradeCardsGrid.tsx"),
  "./components/mockups/closed-positions/TradeJournalTimeline.tsx": () => import("../components/mockups/closed-positions/TradeJournalTimeline.tsx")
};
